flags:
    text:
        integer-simple: false
packages:
- '.'
extra-deps:
    - mtl-2.2.1
    - network-2.6.2.1
    - stm-2.4.4
    - transformers-0.4.2.0
    - attoparsec-0.13.0.1
    - hashable-1.2.3.3
    - scientific-0.3.3.8
    - text-1.2.1.3

resolver: ghc-7.10
